name: Build

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.10'

    - uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-2.6-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-2.6-
          gems-${{ runner.os }}-

    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      env:
        BUNDLE_FORCE_RUBY_PLATFORM: true
    - run: bundle exec middleman build
